### PR TITLE
Set up website auto-rendering via GitHub Actions

### PR DESCRIPTION
**Pull request by Bisaloo**
Once this is merged and we have confirmed that the HTML document is properly sent to `gh-pages`:

- repo settings should be updated to render site from the `gh-pages` branch rather than from `main`
- `index.html` in `main` can be deleted

### CODE REVIEW

**Comment by SaranjeetKaur** [comment]
> Once this is merged and we have confirmed that the HTML document is properly sent to `gh-pages`:
> 
> * repo settings should be updated to render site from the `gh-pages` branch rather than from `main`
> * `index.html` in `main` can be deleted

@sdruskat - could you please take a look at those settings whenever possible?

**Comment by sdruskat** [comment]
Thanks @SaranjeetKaur. I'm testing this just now, but the GH Deploy Plugin seems to fail atm (https://github.com/sdruskat/software-authorship/actions/runs/5001120923/jobs/8959395656). Looking into it.

**Comment by sdruskat** [comment]
@SaranjeetKaur This works now (had to set write permissions in the GH Actions workflow). Content is deployed to gh-pages and served from there.

**Comment by SaranjeetKaur** [comment]
Awesome! Thanks @sdruskat!

**Pull request merged**
